import type { App } from 'vue'
import {
  create,
  NButton,
  NCard,
  NDataTable,
  NForm,
  NFormItem,
  NInput,
  NInputNumber,
  NSelect,
  NDatePicker,
  NModal,
  NDrawer,
  NDropdown,
  NAvatar,
  NBadge,
  NTag,
  NSpace,
  NGrid,
  NGi,
  NStatistic,
  NProgress,
  NSpin,
  NEmpty,
  NPagination,
  NMenu,
  NLayout,
  NLayoutSider,
  NLayoutContent,
  NLayoutHeader,
  NLayoutFooter,
  NNotificationProvider,
  NMessageProvider,
  NDialogProvider,
  NLoadingBarProvider,
  NConfigProvider,
  NTabs,
  NTabPane,
  NAlert,
  NSwitch,
  NCheckbox,
  NRadio,
  NRadioGroup,
  NUpload,
  NImage,
  NScrollbar,
  NDivider,
  NBreadcrumb,
  NBreadcrumbItem,
  NTooltip,
  NPopover,
  NPopconfirm,
} from 'naive-ui'

const naive = create({
  components: [
    NButton, NCard, NDataTable, NForm, NFormItem, NInput, NInputNumber,
    NSelect, NDatePicker, NModal, NDrawer, NDropdown, NAvatar, NBadge,
    NTag, NSpace, NGrid, NGi, NStatistic, NProgress, NSpin, NEmpty,
    NPagination, NMenu, NLayout, NLayoutSider, NLayoutContent, NLayoutHeader,
    NLayoutFooter, NNotificationProvider, NMessageProvider, NDialogProvider,
    NLoadingBarProvider, NConfigProvider, NTabs, NTabPane, NAlert, NSwitch,
    NCheckbox, NRadio, NRadioGroup, NUpload, NImage, NScrollbar, NDivider,
    NBreadcrumb, NBreadcrumbItem, NTooltip, NPopover, NPopconfirm,
  ],
})

export function setupNaiveUI(app: App) {
  app.use(naive)
}
